### ISSUE TITLE
Setup the Blog

### ISSUE THREAD

**Issue by Copposhop** [CAuDri/caudri.github.io#3]
We want to release articles/blog posts about our competition and other related events.
Our Jekyll theme already provides a blog post template and an auto-generated archive: [https://phlow.github.io/feeling-responsive/blog/](https://phlow.github.io/feeling-responsive/blog/).

**Comment by Copposhop** [comment]
Related issues: #2 #19
Dev branch: #blog

**Comment by Jajaho** [comment]
### Implications for the landing page:
Our landing page (_index.md_) uses the _frontpage.html_ layout, in which up to **3 widgets** are predefined to link to other sections on our page. We can use them to link to the _blog_, _regulations_ and _join us_ pages or alternatively also to a page for the next contest.

Currently, if at least one post exists, the frontpage.html also displays a **blog section** before the content area.
We should move the welcome message above this display.

**Comment by Jajaho** [comment]
Currently, if at least one post exists, the _frontpage.html_ also displays a blog section before the content area. 
We should move the welcome message above this display.

**Comment by Jajaho** [comment]
### ToDo List
- [ ] Landing page: The blog should be featured nicely on the landing page with either a widget or an overview of the lastest posts.
- [ ] Side bar: The predefined sidebar must be adjusted.
- [ ] Ad space: Maybe use it for the newsletter.
- [ ] Rename Blog to News

**Comment by Jajaho** [comment]
#24
